/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Config: typeof import('./src/components/Button/config.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    copy: typeof import('./src/components/Button copy/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    Left: typeof import('./src/components/Left.vue')['default']
    Right: typeof import('./src/components/Right.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
  }
}
